version: '3.8'

services:
  # Servidor de sinalização
  signaling-server:
    build: 
      context: ./server
      dockerfile: ../Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - chat-network

  # Frontend React (desenvolvimento)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_SIGNALING_SERVER=ws://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - signaling-server
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
